mobile layout for "how it works", "interaction", "features"
tr-ann/responsive-web-page-ask-it pull request #9
Opened 2020-11-09 15:27 UTC by tr-ann

2020-11-11 18:02 UTC, iharszh requested changes

2020-11-11 18:02 UTC, iharszh commented on src/styles/about-us/tablet.scss
> +  .about-us-info__statistics-container {
this can be nested under `.about-us-info` selector higher

2020-11-11 18:02 UTC, iharszh commented on src/index.html
> -          <div class="events__card">
are you sure you want to delete this whole section?

2020-11-11 18:02 UTC, iharszh commented on src/index.html
> -    <footer id="footer" class="footer">
same thing, are you sure you want to delete the footer?

2020-11-11 18:02 UTC, iharszh commented on src/styles/guide/mobile.scss
> +@media (max-device-width: $mobile-max-width) {
please use `max-width` query instead
`max-width` query depends on viewport parameters and `max-device-width` depends on actual width of the device. this may not work when you rotate the device or change viewport width somehow

2020-11-11 18:02 UTC, iharszh commented on src/styles/header/mobile.scss
> +@media (max-device-width: $mobile-max-width) {
please use `max-width` query instead

2020-11-11 18:02 UTC, iharszh commented on src/styles/interaction/tablet.scss
> +      padding: 6rem 0rem 0rem;
you can use just `6rem 0 0` here

2020-11-11 18:02 UTC, iharszh commented on src/styles/landing/desktop.scss
> +  background: linear-gradient(rgba(24, 31, 99, 0.7), rgba(17, 50, 80, 0.7)),
please add colors to variables or reuse existing variables if they exist

2020-11-11 18:02 UTC, iharszh commented on src/styles/landing/mobile.scss
> +@media (max-device-width: $mobile-max-width) {
please use `max-width` as a query param

2020-11-12 12:57 UTC, iharzh approved these changes

2020-11-12 12:57 UTC, merged